openapi: 3.0.0
info:
  title: Storyline Memory Service
  version: 1.0.0
  description: API for the Storyline Memory Service
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
  /memory/semantic:
    post:
      summary: Add content to semantic memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                metadata:
                  type: object
      responses:
        '201':
          description: Content added to memory
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: Retrieve content from semantic memory
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved content
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /memory/graph:
    post:
      summary: Add a conversation to the graph memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '201':
          description: Conversation added to graph
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: Retrieve related entities from the graph memory
      parameters:
        - name: entity
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved related entities
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /memory/query:
    get:
      summary: Retrieve content from memory using a hybrid query
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved content
        '400':
          description: Bad request
        '500':
          description: Internal server error
